language: python

python:
- 2.7
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- pypy-5.3.1

install:
- pip install --upgrade setuptools
- pip install coveralls pytest pytest-runner pylint
- pip install ./carmin-server

script:
- cd ./carmin-server
- pylint **/*.py --errors-only
- coverage run --source carmin-server setup.py pytest

after_success:
- coveralls
