language: python

sudo: required

services:
- docker

python:
- 2.7
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly
- pypy-5.3.1

install:
- pip install --upgrade setuptools
- pip install coveralls pytest
- pip install ./cbrainserver

script:
- cd ./cbrainserver
- coverage run --source carmin_cbrain setup.py pytest

after_success:
- coveralls