language: python

sudo: required

services:
  - docker

before_install:
  - docker build -t carmin:test ./cbrainserver
  - docker run -d -p 5000:80 --name travis_test carmin:test
  - docker ps -a

script:
  - docker exec travis_test pytest
